### ISSUE TITLE
Provide CI builds of Positron Server for Linux

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#1618]
Currently our CI release builds only include macOS desktop builds, e.g.:

https://github.com/posit-dev/positron/releases/tag/2023.10.0-1269

We should start building Linux releases of Positron, too, starting with Positron Server; this is a prerequisite to including Positron inside Posit Workbench.

**Comment by sharon-wang** [comment]
### TODOs
- [ ] Run local debug build successfully https://github.com/posit-dev/positron/issues/4379
- [ ] Run local release build successfully (yes with caveats -- see extensions issue below)
- [ ] Build CI release build successfully 
- [ ] Run CI release build successfully (yes with caveats -- see extensions issue below)
- [ ] Add handling for auto-merging remote and web dependencies
- [ ] At least pyright and quarto extensions (probably all extensions) are erroring with a notification toast on startup with `No valid VS Code version detected: Version string is: 2024.08.0`
- [ ] Update resources/server/favicon.ico for Positron (maybe we can add to positron-product-icons/update-icons.sh to generate the ico file?)

**Comment by sharon-wang** [comment]
## For verification, this PR is the most relevant one: https://github.com/posit-dev/positron/pull/4426

There's a linked linux build PR there which has steps on how to run the build. Please reach out to me if I can clarify anything!

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : Positron Build: Daily Release #61
    OS Version          : Ubuntu

### Test scenario(s) 

Verified with instructions here: https://github.com/posit-dev/positron-builds/pull/49

Link(s) to TestRail test cases run or created:
N/A
