### ISSUE TITLE
Epic: Data Explorer Summary Panel statistics

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#2161]
When the Summary Panel is expanded, it will dynamically calculate and then reveal additional summary statistics for that specific column. This is a lazy operation in the backend as it would otherwise be costly for long/wide datasets.

Summary stats will be right aligned at the decimal place:

```
NA:           15
Median:       14
Mean:         15.7
SD:            2.1
Min:           1.2
Max:          20.3
```

Completed:

- [x] Numeric in R
- [x] Numeric in Python
- [x] String in R
- [x] String in Python
- [x] Date in R
- [x] Date in Python
- [x] Datetime in R
- [x] Datetime in Python
- [x] Boolean in R
- [x] Boolean in Python
- [x] Unknown in R
- [x] Unknown in Python

Parent Categorical: https://github.com/posit-dev/positron/issues/3417
- [x] Factor/Categorical in R 
- [x] Factor/Categorical in Python 

### Number
* Median
* Mean
* Standard Deviation (SD)
* Min
* Max

## Boolean
* TRUE N (%)
* FALSE N (%)

## String
* Empty: N ( this is equivalent to a `""` string - implicit missing)
* Unique (Number of unique strings)

## String sub-category: Categorical/Factor
* Levels - Ordered/Not Ordered + number

## Date or Datetime or time
* Number of unique
* Mean
* Median
* Min
* Max
* If time, timezone

## Array -- holding off for now
* Number of unique

## Struct -- holding off for now
* Number of unique

## Unknown -- holding off for now
* Number of unique

**Comment by wesm** [comment]
Factor/Categorical summary statistics should not delegate to the summary stats for the display type (e.g. ColumnDisplayType.String, or for pandas whatever the type of the categories is). What other items need to be addressed to resolve this issue?

**Comment by jthomasmock** [comment]
I think we can close this out since we've implemented the required items in R/Python and open new issues if there are data types users would like to see.
