### ISSUE TITLE
Epic - Data Explorer: Loading indicator

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#3059]
There are a few loading indicator enhancements that we'd like to surface when doing calculations or other operations.

- [x] https://github.com/posit-dev/positron/issues/2740
- [x] https://github.com/posit-dev/positron/issues/2301
- [x] https://github.com/posit-dev/positron/issues/2947

**Comment by jonvanausdeln** [comment]
All issue have been closed. I gave it all another look and it's all good on all 3 platforms
