### ISSUE TITLE
Epic: Full Test Suite Workflow should use Release build

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#3584]
The current [Full Test Suite workflow](https://github.com/posit-dev/positron/actions/workflows/positron-full-test.yml) pulls `main` and runs against a dev build.  

We should make it run against the nightly release build. We aren't currently sure if it's even possible to run the automation against a release built executable.

Ideas:
* triggered by Release workflow instead of a schedule
* Use release tag if not possible to use the pre-built executable.

- [x] Figure out how to run the tests against a particular release locally - Marie
- [x] How to install it in automation or workflow -  TBD (do we need to install it?)
- [x] How to figure out what build to grab
- [x]  Figure out how to run the tests against a particular release in GitHub Workflows

**Comment by testlabauto** [comment]
```
 git tag --sort=committerdate | grep -E '[0-9]' | tail -1
```

**Comment by jonvanausdeln** [comment]
That's a good point.

**Comment by jlang-311** [comment]
@jlang-311 reminder to take a look at this
