### ISSUE TITLE
Data Explorer: Summary panel histograms for continuous data

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#4061]
The summary panel is useful today for quickly navigating columns or seeing missing data, but we'd also like to show sparkline histograms for a rapid view of the distribution of data. This will initially be focused on true numeric data types (float, int, double, etc.). We can evaluate it for other continuous data, such as date/time, but we'll almost certainly need to account for other data types in a specific way to be most helpful.

Front-end will need:
- [ ] Frontend SVG graphic
- [ ] Reactive to resizing, and will completely disappear if the summary panel is shrunk to min-width

Backend calculation of appropriate number of bins and values within them:
- [x] For R dataframes
- [x] Polars (https://github.com/posit-dev/positron/pull/4189)
- [x] Pandas (https://github.com/posit-dev/positron/pull/4189)

For very wide datasets, backend calculations may need to be lazy to avoid very expensive calculations on initial load. They could be calculated and cached based on the specific columns in focus.

![image](https://github.com/user-attachments/assets/4e6bb0f9-0ded-494d-99fb-9537a0ac86e5)

**Comment by abrahammbs93** [comment]
Do you plan this features to be impleted also for the xts objects?

**Comment by jthomasmock** [comment]
> Do you plan this features to be impleted also for the xts objects?

Our goal is initially any continuous data for which distribution plots such as histograms or density plots are appropriate, typically for counts/density on the y-axis for specific bins/range on the x-axis. This is most appropriate for true numeric data types.

While you can look at distributions for date/time data with a histogram, it could also end up being a separate type of data visualization, e.g., a smoothed time series or a somewhat different representation of a density plot.

Do you have any opinions/preference regarding time-series/date/time data and distribution or other summary plots?

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-83
    OS Version          : OSX

### Test scenario(s) 

Using flights.parquet, checking Python and R and checking the sparklines against each other (feature flag enabled).

Link(s) to TestRail test cases run or created: 
N/A
