### ISSUE TITLE
Epic: Plots in R

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#4734]
- [ ] https://github.com/posit-dev/positron/issues/3915
- [ ] https://github.com/posit-dev/positron/issues/4593
- [ ] https://github.com/posit-dev/positron/issues/3834
- [ ] https://github.com/posit-dev/positron/issues/3698
- [ ] https://github.com/posit-dev/positron/issues/3667
- [ ] https://github.com/posit-dev/positron/issues/3562
- [ ] https://github.com/posit-dev/positron/issues/3214
- [ ] https://github.com/posit-dev/positron/issues/2919
- [ ] https://github.com/posit-dev/positron/issues/2738
- [ ] https://github.com/posit-dev/positron/issues/727
