### ISSUE TITLE
Epic: Positron Web stability

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#4893]
## Stability items

- [x] https://github.com/posit-dev/positron/issues/4851
- [x] https://github.com/posit-dev/positron/issues/4840
- [x] https://github.com/posit-dev/positron/issues/4800
- [x] https://github.com/posit-dev/positron/issues/4888
- [x] https://github.com/posit-dev/positron/issues/5089
- [x] https://github.com/posit-dev/positron/issues/5048
- [x] https://github.com/posit-dev/positron/issues/5045
- [ ] https://github.com/posit-dev/positron/issues/5090
- [ ] https://github.com/posit-dev/positron/issues/4278

**Comment by juliasilge** [comment]
We got almost all of this done ✅ with two remaining issues moved to other milestones.
