### ISSUE TITLE
Jupyter Supervisor known issues

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#4912]
This issue collects known issues & TODOs with the Jupyter Supervisor.

## Missing Functionality

- [x] When kernel startup fails, any output emitted during startup needs to be captured and shown to the user (https://github.com/posit-dev/positron/issues/4960)
- [x] Input prompts (i.e. `readline()`) and friends 
- [x] Attach on startup / sleep on startup (R debugging aids, aka `JupyterKernelExtra`)
- [x] Binary buffer payloads for e.g. IPyWidgets
- [x] Reattach to busy sessions (#1243; partially done but the kernels themselves may need some work to finish)
- [x] Replay lost output (#4577)
- [x] Support for the reticulate workflow (may need the supervisor to have some sort of adoption method for this). https://github.com/posit-dev/positron/issues/5226
- [x] Appears to try to reconnect to sessions after they crash and the browser is reloaded (need to figure out why this is happening)
- [x] Add support for using the supervisor in CI (Github Actions). CI jobs cannot download the supervisor binary since it is currently hosted in a private repository, so we either need to supply a secret to the CI job or host the supervisor binary somewhere else.

 ## Polish/Hygiene

- [x] Option to hide the terminal that hosts the supervisor. Will also need to stream its logs to an output channel so they are still readable.
- [x] Complete & test bearer token workflow
- [x] Mitigate the classic "Jupyter Race Condition" issue by having the server serialize port allocations, or by keeping track of ports that are pending connections and rejecting them if selected by the port picker
- [ ] Shut down sessions gracefully when Positron exits (bizarrely no way to detect a quit from an extension)
- [x] Run kernel under a login shell to ensure shell startup scripts can feed it any needed variables
- [ ] Support on all Linux platforms we care about (might need to copy Ark's approach)
- [x] Find a way to download and run the supervisor in the pull request test suite (not currently possible because the PR CI job does not have access to the private repository that hosts the binaries)

## Other/Aspirational

- [ ] Option to connect to the server over a domain socket or IPC instead of HTTP; the HTTP connection may trip security/firewall rules on desktop platforms and raise security audit concerns on server platforms
- [ ] Option to use an existing (perhaps even non-local) supervisor instead of creating a new one
- [x] Related: option to leave supervisor running in a remote SSH environment to support long-running sessions. https://github.com/posit-dev/positron/issues/4996
- [ ] Hook up console to the supervisor's execution queue (i.e. submit statements to supervisor right away; query queue at startup). https://github.com/posit-dev/positron/issues/1220
- [ ] For performance, use a binary socket instead of a text one and a more compact representation of the data

**Comment by jmcphers** [comment]
These are 90% taken care of now, and we have issues tracking the remainder.
