### ISSUE TITLE
Epic: Auto-Update

### ISSUE THREAD

**Issue by timtmok** [posit-dev/positron#5542]
Positron needs a mechanism to notify a user that an update is available as well as the ability to update itself.

- [x] https://github.com/posit-dev/positron/issues/1837
- [x] https://github.com/posit-dev/positron/issues/5537
- [x] https://github.com/posit-dev/positron/issues/5538
- [x] https://github.com/posit-dev/positron/issues/5540
- [x] https://github.com/posit-dev/positron/issues/5541

**Comment by juliasilge** [comment]
We have finished out this epic! 🎉
